### ISSUE TITLE
Parts lists

### ISSUE THREAD

**Issue by valerioangelici** [openhardwarecoza/esp8266-PROJECTS#1]
Hi,
I am looking at the homeNodeInline but I cannot find a parts list to know wich parts you are using to build it (for example the 3.3v regulator), could you help me to reproduce the parts list? I have a lot of 0805 and 0603 10k resistors, do you think I can change the ones you selected with these?
thanks

**Comment by openhardwarecoza** [comment]
1117-33 regulator. It was never a finished project so use at own risk (and use your skills to select values)

**Comment by valerioangelici** [comment]
ok thanks! you planned to use the G3MB-202P ssr relay? have you tried them with the wiring on the schematics? (directly from the esp without a transistor)

**Comment by openhardwarecoza** [comment]
. It was never a finished project so use at own risk (and use your skills to select values)

**Comment by valerioangelici** [comment]
ok, I thought you could help me to avoid some tests but it seems I am getting a copy-paste... so I will try to solve myself.
thanks
