### ISSUE TITLE
How to control relay in program?

### ISSUE THREAD

**Issue by lsahidin** [openhardwarecoza/esp8266-PROJECTS#3]
Hi, by your design SSR is connected to GPIO4 with 10K and 3.3v. how to control relay? give HIGH or LOW on the GPIO4? to open relay need to give HIGH and to activate relay give LOW ?

**Comment by openhardwarecoza** [comment]
Depends on your specific relay... Test it. Mine is active low.

**Comment by lsahidin** [comment]
Same relay. so the GPIO4 will always HIGH? or default HIGH by 3.3v ? I will use 5v
